spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
logging:
  level:
    com.gali.thymeleaf : debug
